### ISSUE TITLE
Game crashes on startup on computers with modern Radeon video cards

### ISSUE THREAD

**Issue by de-ko** [nhydock/Storymode#17]
The console output is

Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
        at java.lang.Class.getMethod0(Class.java:2866)
        at java.lang.Class.getMethod(Class.java:1676)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.ApplicationListener
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 6 more

**Comment by nhydock** [comment]
What version of the game are you playing and what platform did you acquire it from?

**Comment by de-ko** [comment]
I got it from Steam on Windows. Not sure how to check the game version, though.
I've re-installed it, and now the console output is this:

Setting breakpad minidump AppID = 386710
Steam_SetMinidumpSteamID:  Caching Steam ID:  XXX [API loaded no]
java.lang.IllegalArgumentException: Error compiling shader: Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

Fragment shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated


        at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:157)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:120)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:73)
        at com.nhydock.storymode.Storymode.create(Storymode.java:98)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:255)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:222)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
        at com.nhydock.storymode.DesktopLauncher.main(DesktopLauncher.java:40)
Exception in thread "main" java.lang.NullPointerException
        at com.nhydock.storymode.Storymode.pause(Storymode.java:297)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.dispose(Lwjgl3Window.java:263)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.cleanup(Lwjgl3Application.java:148)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:99)
        at com.nhydock.storymode.DesktopLauncher.main(DesktopLauncher.java:40)
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by nhydock** [comment]
Alright, that's an error with the shader is something that should have been just recently fixed with my latest update which pushed around 11pm EST.  That itself is an error with libgdx that happens on some modern AMD graphics cards.  Please make sure you have the following files

```
assets
└── shaders
    ├── default.vertex.glsl
    └── default.fragment.glsl
```

If you don't have those files, then you need to update again.  I added some default shaders with the glsl version number explicitly declared so as to override libgdx's defaults, which do not have the version declared and are thus causing some cards to crash while trying to play the game ever since the switch to LWJGL3 and GLSL3.

**Comment by de-ko** [comment]
I have those files, and they both have version defined in them, however the game still does not launch with the exact same error message.

>type assets\shaders\default.vertex.glsl
#version 130
...

>storymode.bat
java.lang.IllegalArgumentException: Error compiling shader: Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated
...
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:157)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:120)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:73)
        at com.nhydock.storymode.Storymode.create(Storymode.java:98)
...

There's some workaround posted at the end of this thread, may be it would be useful:
https://github.com/libgdx/libgdx/issues/3559#issuecomment-202076583

**Comment by nhydock** [comment]
I could try putting that shader prepend onto it.  Having it actually specified in the shader files should have solved that problem, but I guess not.  The craziest issue here is that it's still using createDefaultShader even though I'm specifying one to use explicitly.

**Comment by nhydock** [comment]
Nevermind, I know why it's still using createDefaultShader.  I need to feed the shader into its constructor instead of just setting it at a later point because it attempts to compile the built-in one before it's even used.  It's a simple change up of line ordering.  I'll push up the fix in a few hours once I have access to my development environment.

**Comment by de-ko** [comment]
Great news!
Let me know I can assist in testing the fix.

**Comment by nhydock** [comment]
update has been pushed, hopefully this fixes things

**Comment by de-ko** [comment]
Sorry for bringing bad news, but the crash is still there.
However, it now happens with different stack trace: LoadScreen.java:40 is now calling gdx.scenes.scene2d.Stage().

> at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:157)
> at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:120)
> at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:73)
> at com.badlogic.gdx.scenes.scene2d.Stage.<init>(Stage.java:83)
> at com.nhydock.storymode.service.implementations.LoadScreen.onRegister(LoadScreen.java:40)
> at github.nhydock.ssm.ServiceManager.register(ServiceManager.java:48)
> at com.nhydock.storymode.Storymode.create(Storymode.java:128)
>...

**Comment by nhydock** [comment]
Alright, one more time.  Ended up throwing in a few other bug fixes too.

**Comment by de-ko** [comment]
Seems to work now.
Thank you!
